# Generated by Django 5.1.4 on 2025-04-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0003_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horas.profile'),
        ),
    ]
