# Generated by Django 5.1.4 on 2025-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0004_registroasistencia_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='horas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
