# Generated by Django 5.1.4 on 2025-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0005_actividad_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='valor_horas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
